<?php
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "<head>\n";
echo "<meta 	charset=\"utf-8\">\n";
echo "	<title>Animaciones CSS3</title>\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilos.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "	<div class=\"titulo\">\n";
echo "		<CENTER><H1><B>Reyes Vega Angel Leonardo</B></H1></CENTER>\n";
echo "	</div>\n";
echo "	<div class=\"Foto\">\n";
echo "		<CENTER><img src=\"js/foto.jpg\" alt=\"Foto personal\"></CENTER>\n";
echo "	</div>\n";
echo "	<HR>\n";
echo "	<div class=\"Acercade\">\n";
echo "		<H2>Acerca de</H2>\n";
echo "		Estudiante en Nivel Medio Superior en el Centro de Estudios Cientificos y Tecnologicos Numero<BR>\n";
echo "		9 \"Juan de Dios Batiz Paredes\" actualmente cursando la carrera tecnica de Programación<BR>\n";
echo "		misma de la cual ha cursado en su tercer semestre las materias de Programación Orientada a<BR>\n";
echo "		Objetos (POO), Laboratorio de Proyectos de Tecnologias de la Información I y Administración<BR>\n";
echo "		de Proyectos de Tecnologias de la Información I. Actualmente cursando cuarto semestre con<BR>\n";
echo "		las materias de Programación y Servicios Web (PSW), Bases de Datos, Laboratorio de Proyectos<BR>\n";
echo "		de la Información II y Tecnicas de Programación Personal con Calidad (TPPC).\n";
echo "	</div>\n";
echo "	<HR>\n";
echo "	<div class=\"Experiencia\">\n";
echo "		<H2>Experiencia</H2>\n";
echo "		<UL>\n";
echo "			<LI>\n";
echo "				Computación Basica I (Microsoft Word y Microsoft Power Point).\n";
echo "			</LI>\n";
echo "			<LI>\n";
echo "				Computación Basica II (Microsoft Excel y HTML).\n";
echo "			</LI>\n";
echo "			<LI>\n";
echo "				Programación Orientada a Objetos (POO).\n";
echo "			</LI>\n";
echo "			<LI>\n";
echo "				Laboratorio de Proyectos de Tecnologias de la Información I.\n";
echo "			</LI>\n";
echo "			<LI>\n";
echo "				Administración de Proyectos de Tecnologias de la Información I.\n";
echo "			</LI>\n";
echo "		</UL>\n";
echo "	</div>\n";
echo "	<HR>\n";
echo "	<div class=\"Educacion\">\n";
echo "		<H2>Educacion</H2>\n";
echo "		<a href=\"https://www.institutocrisol.edu.mx/\"><img src=\"js/crisol.jpg\" align=\"left\" height=\"100\" width=\"100\" alt=\"Instituto Crisol\"></a>\n";
echo "		Instituto Crisol<BR>\n";
echo "		2014-2017<BR>\n";
echo "		Escuela Nivel Preescolar, Primaria y Secundaria<BR>\n";
echo "		Escuela Catolica<BR>\n";
echo "		Promedio de 8.3<BR>\n";
echo "		<BR>\n";
echo "		<BR>\n";
echo "		<BR>\n";
echo "		<a href=\"https://www.cecyt9.ipn.mx/\"><img src=\"js/cecyt.jpg\" align=\"left\" height=\"100\" width=\"100\" alt=\"CECYT 9\"></a>\n";
echo "		Centro de Estudios Cientificos y Tecnologicos Numero 9 \"Juan de Dios Batiz Paredes\"<BR>\n";
echo "		2017-Actualidad<BR>\n";
echo "		Escuela Nivel Medio Superior<BR>\n";
echo "		Promedio actual de 7.96<BR>\n";
echo "		<BR>\n";
echo "		<BR>\n";
echo "		<BR>\n";
echo "		<BR>\n";
echo "	</div>\n";
echo "	<HR>\n";
echo "	<div class=\"Idiomas\">\n";
echo "		<H2>Idiomas</H2>\n";
echo "		<B>Español</B><BR>\n";
echo "		Lengua Nativa<BR>\n";
echo "		<BR>\n";
echo "		<B>Ingles</B><BR>\n";
echo "		Lengua Secundaria<BR>\n";
echo "		<BR>\n";
echo "	</div>\n";
echo "</body>\n";
echo "</html>\n";

?>